In [1]:
import numpy as np
import pandas as pd

In [2]:
path="/content/drive/MyDrive/mulcam_bigdata/3조 : 최종 프로젝트/공용/AI명령어 데이터/명령어 음성(노인남여)/AI비서 데이터_50대_validation.csv"

In [3]:
pd.read_csv(path)

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,보고 있는 영상 정지시켜 줘.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6001-01-01-KSM-F-05-A.wav
1,다음 주까지 날씨가 어때?,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6002-01-01-KSM-F-05-A.wav
2,나 대신 점등해 줘.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6003-01-01-KSM-F-05-A.wav
3,이번 주 대체로 흐린지 궁금해.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6004-01-01-KSM-F-05-A.wav
4,지금 당장 취침 등 꺼 줘.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6005-01-01-KSM-F-05-A.wav
...,...,...,...,...,...,...,...,...
142362,내가 설정해 놓은 온도로 맞춰 줘.,Female,20~29,대전/세종/충청/강원,충청,가정,가정,script1_g_0248-6996-01-01-HYY-F-04-B.wav
142363,성북구에서 우리 집까지 교통 상황 체크해.,Female,20~29,대전/세종/충청/강원,충청,가정,가정,script1_g_0248-6997-01-01-HYY-F-04-B.wav
142364,오디오북 취침 모드 온 해 줘.,Female,20~29,대전/세종/충청/강원,충청,가정,가정,script1_g_0248-6998-01-01-HYY-F-04-B.wav
142365,지금 차량 얼마나 막혀?,Female,20~29,대전/세종/충청/강원,충청,가정,가정,script1_g_0248-6999-01-01-HYY-F-04-B.wav
142366,커피 머신에 원두 찌꺼기 청소해놔 줘,Female,20~29,대전/세종/충청/강원,충청,가정,가정,script1_g_0248-7000-01-01-HYY-F-04-B.wav

In [4]:
raw = pd.read_csv(path)
raw.head()

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,보고 있는 영상 정지시켜 줘.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6001-01-01-KSM-F-05-A.wav
1,다음 주까지 날씨가 어때?,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6002-01-01-KSM-F-05-A.wav
2,나 대신 점등해 줘.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6003-01-01-KSM-F-05-A.wav
3,이번 주 대체로 흐린지 궁금해.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6004-01-01-KSM-F-05-A.wav
4,지금 당장 취침 등 꺼 줘.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6005-01-01-KSM-F-05-A.wav

In [5]:
df = raw.copy()
df.head()

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,보고 있는 영상 정지시켜 줘.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6001-01-01-KSM-F-05-A.wav
1,다음 주까지 날씨가 어때?,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6002-01-01-KSM-F-05-A.wav
2,나 대신 점등해 줘.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6003-01-01-KSM-F-05-A.wav
3,이번 주 대체로 흐린지 궁금해.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6004-01-01-KSM-F-05-A.wav
4,지금 당장 취침 등 꺼 줘.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6005-01-01-KSM-F-05-A.wav

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142367 entries, 0 to 142366
Data columns (total 8 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   대화      142367 non-null  object
 1   성별      142367 non-null  object
 2   연령대     142367 non-null  object
 3   지역      142367 non-null  object
 4   사투리     142367 non-null  object
 5   녹음환경    142367 non-null  object
 6   소음환경    142367 non-null  object
 7   파일이름    142367 non-null  object
dtypes: object(8)
memory usage: 8.7+ MB

#LDA 분석

In [7]:
!pip install -q pandas numpy scikit-learn konlpy pyLDAvis

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 72.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 66.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 27.8 MB/s eta 0:00:00

In [8]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis.lda_model

# 1. 텍스트 전처리
def preprocess_text(text):
    okt = Okt()
    tokens = okt.nouns(text)  # 명사만 추출
    return ' '.join(tokens)

df['preprocessed'] = df['대화'].apply(preprocess_text)

# 2. 단어 벡터화
vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
doc_term_matrix = vectorizer.fit_transform(df['preprocessed'])

# 3. LDA 모델 학습
lda_model = LatentDirichletAllocation(n_components=5, random_state=42)
lda_output = lda_model.fit_transform(doc_term_matrix)

In [9]:
# 4. 결과 시각화
pyLDAvis.enable_notebook()
vis = pyLDAvis.lda_model.prepare(lda_model, doc_term_matrix, vectorizer)
pyLDAvis.display(vis)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [10]:
# 5. 토픽별 주요 단어 출력
def print_topics(model, vectorizer, top_n=10):
    for idx, topic in enumerate(model.components_):
        print(f"Topic {idx + 1}:")
        print([(vectorizer.get_feature_names_out()[i], topic[i])
                for i in topic.argsort()[:-top_n - 1:-1]])

print_topics(lda_model, vectorizer)

Topic 1:
[('상황', 4906.19672304817), ('교통', 4353.199421948955), ('현재', 4078.29430029885), ('부탁', 3951.6713944196354), ('플레이', 3836.199136717875), ('리스트', 3552.1991501389034), ('경로', 2491.2279386158584), ('주가', 2176.1990830033537), ('추천', 2144.198090218424), ('도로', 1703.514505261106)]
Topic 2:
[('오늘', 7006.15001140323), ('블라인드', 4230.8491254479295), ('토스터', 3812.4246824419324), ('날씨', 2787.3125748094653), ('환율', 2622.807797102646), ('뉴스', 1790.067979112186), ('제일', 1683.1959256097102), ('현재', 1399.1043429269196), ('정보', 1336.8135534301782), ('요약', 1233.6104440216845)]
Topic 3:
[('내일', 6937.05425532116), ('커피', 6024.198608702342), ('경기', 5088.198135766461), ('즐겨찾기', 3766.1999318564613), ('머신', 3404.1995076690664), ('일정', 3223.197595242426), ('오늘', 2734.5744376648063), ('얼마나', 2139.958481034638), ('지금', 1966.020156146125), ('재생', 1882.2484554907323)]
Topic 4:
[('사고', 7271.794765137011), ('목소리', 3210.1997488256643), ('온도', 2593.541443645147), ('티브이', 2397.1974652840904), ('확인', 2385.2165102813024), ('오디오북', 2124.723009097841), ('설정', 2017.6139405414715), ('체크', 1816.4457319595906), ('보일러', 1720.198948791766), ('이제', 1715.1971010330747)]
Topic 5:
[('오디오북', 8856.675312398733), ('지금', 6667.22161622903), ('모드', 6149.690525357158), ('날씨', 5689.311766025436), ('이번', 5201.143514199709), ('취침', 4653.198022067907), ('뉴스', 3810.322054924982), ('에너지', 3419.198864209248), ('절약', 3283.198768777904), ('콘텐츠', 3101.1995084799228)]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

#중복 제거 값 LDA 분석

In [11]:
# 중복 제거
df_clean = df.drop_duplicates(subset=["대화"])
df_clean.reset_index(drop=True, inplace=True)
df_clean.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름,preprocessed
0,보고 있는 영상 정지시켜 줘.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6001-01-01-KSM-F-05-A.wav,보고 영상 정지
1,다음 주까지 날씨가 어때?,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6002-01-01-KSM-F-05-A.wav,다음 주 날씨
2,나 대신 점등해 줘.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6003-01-01-KSM-F-05-A.wav,나 대신 점등
3,이번 주 대체로 흐린지 궁금해.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6004-01-01-KSM-F-05-A.wav,이번 주 대체로
4,지금 당장 취침 등 꺼 줘.,Female,30~39,서울/인천/경기,경기/서울,사무실,사무실,script1_g_0044-6005-01-01-KSM-F-05-A.wav,지금 당장 취침 등

In [12]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3689 entries, 0 to 3688
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   대화            3689 non-null   object
 1   성별            3689 non-null   object
 2   연령대           3689 non-null   object
 3   지역            3689 non-null   object
 4   사투리           3689 non-null   object
 5   녹음환경          3689 non-null   object
 6   소음환경          3689 non-null   object
 7   파일이름          3689 non-null   object
 8   preprocessed  3689 non-null   object
dtypes: object(9)
memory usage: 259.5+ KB

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [13]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis
import pyLDAvis.lda_model

# 1. 텍스트 전처리
def preprocess_text(text):
    if pd.isna(text):
        return ""
    okt = Okt()
    tokens = okt.nouns(str(text))  # 문자열로 변환
    return ' '.join(tokens)

# NaN 값 확인
print("전처리 전 NaN 값의 수:", df_clean['대화'].isna().sum())

# 전처리 적용
df_clean['preprocessed'] = df_clean['대화'].apply(preprocess_text)

# 전처리 후 빈 문자열 확인
print("전처리 후 빈 문자열의 수:", (df_clean['preprocessed'] == '').sum())

# 빈 문자열 제거
df_clean = df_clean[df_clean['preprocessed'] != '']

# 2. 단어 벡터화
vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
doc_term_matrix = vectorizer.fit_transform(df_clean['preprocessed'])

# 3. LDA 모델 학습
lda_model = LatentDirichletAllocation(n_components=5, random_state=42)
lda_output = lda_model.fit_transform(doc_term_matrix)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

전처리 전 NaN 값의 수: 0

<ipython-input-13-3bd4136b0f94>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['preprocessed'] = df_clean['대화'].apply(preprocess_text)

전처리 후 빈 문자열의 수: 4

In [14]:
# 4. 결과 시각화
pyLDAvis.enable_notebook()
vis = pyLDAvis.lda_model.prepare(lda_model, doc_term_matrix, vectorizer)
pyLDAvis.display(vis)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [15]:
# 5. 토픽별 주요 단어 출력
def print_topics(model, vectorizer, top_n=10):
    feature_names = vectorizer.get_feature_names_out()
    for idx, topic in enumerate(model.components_):
        top_features_ind = topic.argsort()[:-top_n - 1:-1]
        top_features = [feature_names[i] for i in top_features_ind]
        weights = topic[top_features_ind]
        print(f"Topic {idx + 1}:")
        for feat, weight in zip(top_features, weights):
            print(f"{feat}: {weight:.4f}")
        print()

print_topics(lda_model, vectorizer)

Topic 1:
오디오북: 262.1986
모드: 164.1971
온도: 130.1986
취침: 127.1984
설정: 93.1969
에너지: 88.1995
절약: 88.1995
콘텐츠: 81.1988
시간: 66.9887
보일러: 66.1990

Topic 2:
사고: 189.1986
지금: 180.0122
오늘: 163.3660
날씨: 149.2431
확인: 134.4710
뉴스: 113.3143
상황: 105.5629
내일: 90.8298
경로: 78.1955
교통: 70.2213

Topic 3:
블라인드: 117.1998
경기: 102.1983
토스터: 93.1985
언제: 63.0662
일정: 58.1978
시간: 31.6273
아침: 31.1982
토스트: 29.1996
도로: 28.2126
가야: 28.1970

Topic 4:
현재: 128.8662
이번: 98.8932
즐겨찾기: 93.1219
주말: 78.1971
플레이: 77.1993
리스트: 70.1992
노래: 64.1982
오디오: 59.9286
날씨: 59.1533
목소리: 41.3955

Topic 5:
커피: 137.1973
머신: 87.1995
내일: 74.5689
소등: 67.1979
정보: 62.1917
공기청정기: 59.1979
점등: 44.1985
오늘: 41.5984
환율: 37.0642
전등: 36.1975

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)