In [1]:
import numpy as np
import pandas as pd

In [2]:
path="/content/drive/MyDrive/mulcam_bigdata/3조 : 최종 프로젝트/공용/AI명령어 데이터/명령어 음성(노인남여)/AI비서 데이터_training.csv"

In [3]:
pd.read_csv(path)

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,이 층에도 편의점 있어?,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15002-02-02-KWEON-M-08-A.wav
1,이 메뉴 한 개만 줘.,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15004-02-02-KWEON-M-08-A.wav
2,이 세트 메뉴 하나만 해 줘.,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15005-02-02-KWEON-M-08-A.wav
3,짜지 않은 음식으로 안내해 줘.,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15006-02-02-KWEON-M-08-A.wav
4,공항 민원 센터가 어디에 있을까?,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15007-02-02-KWEON-M-08-A.wav
...,...,...,...,...,...,...,...,...
526087,마트 몇 시에 영업 시작해?,Female,60~69,부산/대구/울산/경상,경상,가정,가정,s_1000-17996-02-02-KMY-F-08-D.wav
526088,현금 결제로 결제할 거야 가능한지 확인해 줘.,Female,60~69,부산/대구/울산/경상,경상,가정,가정,s_1000-17997-02-02-KMY-F-08-D.wav
526089,된장찌개로 하나 주문해라.,Female,60~69,부산/대구/울산/경상,경상,가정,가정,s_1000-17998-02-02-KMY-F-08-D.wav
526090,돈 뽑으려면 어디로 가야 합니까?,Female,60~69,부산/대구/울산/경상,경상,가정,가정,s_1000-17999-02-02-KMY-F-08-D.wav
526091,응급실로 바로 가야 하니까 빠른 길로 찾아.,Female,60~69,부산/대구/울산/경상,경상,가정,가정,s_1000-18000-02-02-KMY-F-08-D.wav

In [4]:
raw = pd.read_csv(path)
raw.head()

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,이 층에도 편의점 있어?,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15002-02-02-KWEON-M-08-A.wav
1,이 메뉴 한 개만 줘.,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15004-02-02-KWEON-M-08-A.wav
2,이 세트 메뉴 하나만 해 줘.,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15005-02-02-KWEON-M-08-A.wav
3,짜지 않은 음식으로 안내해 줘.,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15006-02-02-KWEON-M-08-A.wav
4,공항 민원 센터가 어디에 있을까?,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15007-02-02-KWEON-M-08-A.wav

In [5]:
df = raw.copy()
df.head()

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,이 층에도 편의점 있어?,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15002-02-02-KWEON-M-08-A.wav
1,이 메뉴 한 개만 줘.,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15004-02-02-KWEON-M-08-A.wav
2,이 세트 메뉴 하나만 해 줘.,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15005-02-02-KWEON-M-08-A.wav
3,짜지 않은 음식으로 안내해 줘.,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15006-02-02-KWEON-M-08-A.wav
4,공항 민원 센터가 어디에 있을까?,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15007-02-02-KWEON-M-08-A.wav

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 526092 entries, 0 to 526091
Data columns (total 8 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   대화      526092 non-null  object
 1   성별      526092 non-null  object
 2   연령대     526092 non-null  object
 3   지역      526092 non-null  object
 4   사투리     526092 non-null  object
 5   녹음환경    526092 non-null  object
 6   소음환경    526092 non-null  object
 7   파일이름    526092 non-null  object
dtypes: object(8)
memory usage: 32.1+ MB

#LDA 분석

In [7]:
!pip install -q pandas numpy scikit-learn konlpy pyLDAvis

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 55.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 67.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 29.0 MB/s eta 0:00:00

In [8]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis.lda_model

# 1. 텍스트 전처리
def preprocess_text(text):
    okt = Okt()
    tokens = okt.nouns(text)  # 명사만 추출
    return ' '.join(tokens)

df['preprocessed'] = df['대화'].apply(preprocess_text)

# 2. 단어 벡터화
vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
doc_term_matrix = vectorizer.fit_transform(df['preprocessed'])

# 3. LDA 모델 학습
lda_model = LatentDirichletAllocation(n_components=5, random_state=42)
lda_output = lda_model.fit_transform(doc_term_matrix)

In [9]:
# 4. 결과 시각화
pyLDAvis.enable_notebook()
vis = pyLDAvis.lda_model.prepare(lda_model, doc_term_matrix, vectorizer)
pyLDAvis.display(vis)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [10]:
# 5. 토픽별 주요 단어 출력
def print_topics(model, vectorizer, top_n=10):
    for idx, topic in enumerate(model.components_):
        print(f"Topic {idx + 1}:")
        print([(vectorizer.get_feature_names_out()[i], topic[i])
                for i in topic.argsort()[:-top_n - 1:-1]])

print_topics(lda_model, vectorizer)

Topic 1:
[('위치', 12195.617327257447), ('직원', 11319.712304360453), ('이용', 8282.49257692651), ('수속', 8152.117036995807), ('카운터', 7860.676621306905), ('어디', 7125.365159883456), ('통신사', 6837.502968756469), ('시설', 6738.780346503261), ('상품', 6133.484100325527), ('식당', 5751.196452641448)]
Topic 2:
[('진료', 23788.19513731281), ('선생님', 16780.198676244574), ('어디', 13668.714085409245), ('차비', 13225.169573958681), ('접수', 11127.40165857418), ('버스', 10964.978971160754), ('강수', 10502.199760055768), ('오늘', 9899.513089499347), ('결제', 9768.346222700864), ('예약', 8507.402694690658)]
Topic 3:
[('시간', 16884.709168533856), ('호텔', 13945.311948681343), ('메뉴', 11111.052205323656), ('비행기', 10995.007904853814), ('공항', 10363.934789873147), ('근처', 10269.12377091337), ('어디', 9552.640241489837), ('직원', 9373.174941645844), ('버스', 7622.6513825881075), ('얼마나', 7469.872655653574)]
Topic 4:
[('마트', 19257.743159918595), ('안내', 16082.93058360054), ('직원', 15858.711701803277), ('부탁', 13535.395283580347), ('주문', 9928.990311911724), ('언제', 8275.333682225506), ('시간', 7316.146949047266), ('주변', 6990.873977615689), ('프론트', 6267.7629112039085), ('음식', 6246.0047654468135)]
Topic 5:
[('가격', 22598.075402310922), ('어디', 21533.0101861446), ('얼마', 13551.01344466355), ('위치', 12231.282474658916), ('여기', 10845.648932083932), ('가야', 10738.784205551823), ('마트', 9677.655961201592), ('다른', 9342.239774882662), ('할인', 9149.39653676975), ('브랜드', 8300.030354054175)]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

#중복 제거 값 LDA 분석

In [11]:
# 중복 제거
df_clean = df.drop_duplicates(subset=["대화"])
df_clean.reset_index(drop=True, inplace=True)
df_clean.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름,preprocessed
0,이 층에도 편의점 있어?,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15002-02-02-KWEON-M-08-A.wav,이 층 편의점
1,이 메뉴 한 개만 줘.,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15004-02-02-KWEON-M-08-A.wav,이 메뉴 개
2,이 세트 메뉴 하나만 해 줘.,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15005-02-02-KWEON-M-08-A.wav,이 세트 메뉴 하나 해
3,짜지 않은 음식으로 안내해 줘.,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15006-02-02-KWEON-M-08-A.wav,음식 안내
4,공항 민원 센터가 어디에 있을까?,Male,60~69,서울/인천/경기,경상,가정,가정,q_0809-15007-02-02-KWEON-M-08-A.wav,공항 민원 센터 어디

In [12]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11302 entries, 0 to 11301
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   대화            11302 non-null  object
 1   성별            11302 non-null  object
 2   연령대           11302 non-null  object
 3   지역            11302 non-null  object
 4   사투리           11302 non-null  object
 5   녹음환경          11302 non-null  object
 6   소음환경          11302 non-null  object
 7   파일이름          11302 non-null  object
 8   preprocessed  11302 non-null  object
dtypes: object(9)
memory usage: 794.8+ KB

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [13]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis
import pyLDAvis.lda_model

# 1. 텍스트 전처리
def preprocess_text(text):
    if pd.isna(text):
        return ""
    okt = Okt()
    tokens = okt.nouns(str(text))  # 문자열로 변환
    return ' '.join(tokens)

# NaN 값 확인
print("전처리 전 NaN 값의 수:", df_clean['대화'].isna().sum())

# 전처리 적용
df_clean['preprocessed'] = df_clean['대화'].apply(preprocess_text)

# 전처리 후 빈 문자열 확인
print("전처리 후 빈 문자열의 수:", (df_clean['preprocessed'] == '').sum())

# 빈 문자열 제거
df_clean = df_clean[df_clean['preprocessed'] != '']

# 2. 단어 벡터화
vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
doc_term_matrix = vectorizer.fit_transform(df_clean['preprocessed'])

# 3. LDA 모델 학습
lda_model = LatentDirichletAllocation(n_components=5, random_state=42)
lda_output = lda_model.fit_transform(doc_term_matrix)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

전처리 전 NaN 값의 수: 0

<ipython-input-13-3bd4136b0f94>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['preprocessed'] = df_clean['대화'].apply(preprocess_text)

전처리 후 빈 문자열의 수: 0

In [14]:
# 4. 결과 시각화
pyLDAvis.enable_notebook()
vis = pyLDAvis.lda_model.prepare(lda_model, doc_term_matrix, vectorizer)
pyLDAvis.display(vis)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [15]:
# 5. 토픽별 주요 단어 출력
def print_topics(model, vectorizer, top_n=10):
    feature_names = vectorizer.get_feature_names_out()
    for idx, topic in enumerate(model.components_):
        top_features_ind = topic.argsort()[:-top_n - 1:-1]
        top_features = [feature_names[i] for i in top_features_ind]
        weights = topic[top_features_ind]
        print(f"Topic {idx + 1}:")
        for feat, weight in zip(top_features, weights):
            print(f"{feat}: {weight:.4f}")
        print()

print_topics(lda_model, vectorizer)

Topic 1:
직원: 864.2040
마트: 552.8700
알레르기: 233.1987
확인: 220.0326
어디: 198.3293
호출: 152.6261
휠체어: 140.1447
시외: 135.1940
달라: 126.1986
음식: 123.8316

Topic 2:
시간: 434.5431
공항: 324.1985
비행기: 276.1605
수속: 210.8209
호텔: 204.5655
언제: 166.3317
카운터: 161.1088
얼마나: 157.8084
출발: 132.0923
항공: 128.1961

Topic 3:
얼마: 507.1974
가격: 469.7081
할인: 271.1970
차비: 226.1981
다른: 222.1982
브랜드: 183.1994
결제: 161.3610
비교: 154.1980
식당: 141.4669
계산: 123.1710

Topic 4:
진료: 526.1990
선생님: 360.1990
접수: 307.1556
언제: 307.0650
메뉴: 233.1956
시간: 218.8549
강수: 218.1998
의사: 194.1781
부탁: 191.6057
오늘: 174.4397

Topic 5:
어디: 1044.1127
위치: 638.1666
안내: 446.2003
가야: 334.7866
주차: 331.1948
공항: 297.2003
여기: 270.4505
근처: 262.1040
버스: 247.7717
부탁: 182.1102

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)