In [1]:
import numpy as np
import pandas as pd

In [2]:
path="/content/drive/MyDrive/mulcam_bigdata/3조 : 최종 프로젝트/공용/AI명령어 데이터/명령어 음성(노인남여)/AI비서 데이터_validation.csv"

In [3]:
pd.read_csv(path)

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,운동으로 체조 하려는데 도와 주면 좋겠네.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12001-02-01-BHJ-F-08-A.wav
1,알람 그만 울려 줘.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12002-02-01-BHJ-F-08-A.wav
2,내가 따라 할 만한 건강 체조 틀어 봐.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12003-02-01-BHJ-F-08-A.wav
3,나 땡벌 노래 부를게.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12004-02-01-BHJ-F-08-A.wav
4,동네 맛집 찾아서 나한테 알려 줘.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12005-02-01-BHJ-F-08-A.wav
...,...,...,...,...,...,...,...,...
83690,오늘 열 시 케이비에스 드라마 예약해 줄래?,Female,over70,서울/인천/경기,경기/서울,가정,가정,n_0878-12996-02-01-KCJ-F-09-A.wav
83691,뉴스 나오는 라디오로 주파수 변경해 줘.,Female,over70,서울/인천/경기,경기/서울,가정,가정,n_0878-12997-02-01-KCJ-F-09-A.wav
83692,구구단으로 내가 이기나 네가 이기나 해 보자.,Female,over70,서울/인천/경기,경기/서울,가정,가정,n_0878-12998-02-01-KCJ-F-09-A.wav
83693,끝말 이어 말하기 해 줘.,Female,over70,서울/인천/경기,경기/서울,가정,가정,n_0878-12999-02-01-KCJ-F-09-A.wav
83694,딸이랑 한 대화 전문 보여 줘.,Female,over70,서울/인천/경기,경기/서울,가정,가정,n_0878-13000-02-01-KCJ-F-09-A.wav

In [4]:
raw = pd.read_csv(path)
raw.head()

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,운동으로 체조 하려는데 도와 주면 좋겠네.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12001-02-01-BHJ-F-08-A.wav
1,알람 그만 울려 줘.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12002-02-01-BHJ-F-08-A.wav
2,내가 따라 할 만한 건강 체조 틀어 봐.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12003-02-01-BHJ-F-08-A.wav
3,나 땡벌 노래 부를게.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12004-02-01-BHJ-F-08-A.wav
4,동네 맛집 찾아서 나한테 알려 줘.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12005-02-01-BHJ-F-08-A.wav

In [5]:
df = raw.copy()
df.head()

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,운동으로 체조 하려는데 도와 주면 좋겠네.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12001-02-01-BHJ-F-08-A.wav
1,알람 그만 울려 줘.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12002-02-01-BHJ-F-08-A.wav
2,내가 따라 할 만한 건강 체조 틀어 봐.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12003-02-01-BHJ-F-08-A.wav
3,나 땡벌 노래 부를게.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12004-02-01-BHJ-F-08-A.wav
4,동네 맛집 찾아서 나한테 알려 줘.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12005-02-01-BHJ-F-08-A.wav

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83695 entries, 0 to 83694
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   대화      83695 non-null  object
 1   성별      83695 non-null  object
 2   연령대     83695 non-null  object
 3   지역      83695 non-null  object
 4   사투리     83695 non-null  object
 5   녹음환경    83695 non-null  object
 6   소음환경    83695 non-null  object
 7   파일이름    83695 non-null  object
dtypes: object(8)
memory usage: 5.1+ MB

#LDA 분석

In [7]:
!pip install -q pandas numpy scikit-learn konlpy pyLDAvis

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 27.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 35.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 18.2 MB/s eta 0:00:00

In [8]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis.lda_model

# 1. 텍스트 전처리
def preprocess_text(text):
    okt = Okt()
    tokens = okt.nouns(text)  # 명사만 추출
    return ' '.join(tokens)

df['preprocessed'] = df['대화'].apply(preprocess_text)

# 2. 단어 벡터화
vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
doc_term_matrix = vectorizer.fit_transform(df['preprocessed'])

# 3. LDA 모델 학습
lda_model = LatentDirichletAllocation(n_components=5, random_state=42)
lda_output = lda_model.fit_transform(doc_term_matrix)

In [9]:
# 4. 결과 시각화
pyLDAvis.enable_notebook()
vis = pyLDAvis.lda_model.prepare(lda_model, doc_term_matrix, vectorizer)
pyLDAvis.display(vis)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [10]:
# 5. 토픽별 주요 단어 출력
def print_topics(model, vectorizer, top_n=10):
    for idx, topic in enumerate(model.components_):
        print(f"Topic {idx + 1}:")
        print([(vectorizer.get_feature_names_out()[i], topic[i])
                for i in topic.argsort()[:-top_n - 1:-1]])

print_topics(lda_model, vectorizer)

Topic 1:
[('모드', 3611.1909192759185), ('외출', 2978.7254515427862), ('전화', 1944.198603725376), ('방범', 1600.1993096636197), ('지금', 1421.540019819687), ('자막', 1328.5044340683726), ('공기', 1318.1997084680147), ('청정기', 823.199961648456), ('상황', 666.1977354333882), ('에어컨', 588.1866875049432)]
Topic 2:
[('내일', 2892.500168836541), ('알람', 2523.31364319787), ('뉴스', 2279.776012913086), ('오늘', 1867.9144271781465), ('이제', 1744.1942839311173), ('예약', 1564.674607632437), ('날씨', 1259.846244541399), ('지금', 1254.0550850981951), ('경기', 1104.1797106142667), ('설법', 1077.6178738341)]
Topic 3:
[('이번', 2115.1973916991496), ('오늘', 2004.472444252742), ('메시지', 1817.9617002644216), ('운세', 1775.1988872940565), ('일정', 1478.3246898039556), ('번호', 1285.8839502537933), ('지금', 1193.4762439707636), ('언제', 1092.1668781663834), ('땡벌', 1075.197199570554), ('확인', 1037.6029224476474)]
Topic 4:
[('예약', 3624.7087333948416), ('방송', 1677.1955877928158), ('설정', 1672.1844122771224), ('노래', 1591.5767829101046), ('재생', 1497.1980861849688), ('영상', 1410.1971051640273), ('명상', 1246.1988536580702), ('부탁', 1127.4144777370439), ('경기', 1065.8605600213602), ('빌보드', 925.198406249857)]
Topic 5:
[('빨래', 2270.079589982645), ('티브이', 1758.1962078039805), ('메일', 1416.1987514290752), ('시간', 1397.286983950207), ('시작', 1339.2529496381042), ('확인', 1326.3541850880245), ('자동', 1236.9893823029663), ('세탁', 1163.198503722734), ('체조', 1091.3708242707394), ('회전', 1090.199671011169)]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

#중복 제거 값 LDA 분석

In [11]:
# 중복 제거
df_clean = df.drop_duplicates(subset=["대화"])
df_clean.reset_index(drop=True, inplace=True)
df_clean.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름,preprocessed
0,운동으로 체조 하려는데 도와 주면 좋겠네.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12001-02-01-BHJ-F-08-A.wav,운동 체조 도
1,알람 그만 울려 줘.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12002-02-01-BHJ-F-08-A.wav,알람
2,내가 따라 할 만한 건강 체조 틀어 봐.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12003-02-01-BHJ-F-08-A.wav,내 만 건강 체조
3,나 땡벌 노래 부를게.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12004-02-01-BHJ-F-08-A.wav,나 땡벌 노래
4,동네 맛집 찾아서 나한테 알려 줘.,Female,60~69,서울/인천/경기,경기/서울,가정,가정,n_0310-12005-02-01-BHJ-F-08-A.wav,동네 맛집 나

In [12]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2157 entries, 0 to 2156
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   대화            2157 non-null   object
 1   성별            2157 non-null   object
 2   연령대           2157 non-null   object
 3   지역            2157 non-null   object
 4   사투리           2157 non-null   object
 5   녹음환경          2157 non-null   object
 6   소음환경          2157 non-null   object
 7   파일이름          2157 non-null   object
 8   preprocessed  2157 non-null   object
dtypes: object(9)
memory usage: 151.8+ KB

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [13]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis
import pyLDAvis.lda_model

# 1. 텍스트 전처리
def preprocess_text(text):
    if pd.isna(text):
        return ""
    okt = Okt()
    tokens = okt.nouns(str(text))  # 문자열로 변환
    return ' '.join(tokens)

# NaN 값 확인
print("전처리 전 NaN 값의 수:", df_clean['대화'].isna().sum())

# 전처리 적용
df_clean['preprocessed'] = df_clean['대화'].apply(preprocess_text)

# 전처리 후 빈 문자열 확인
print("전처리 후 빈 문자열의 수:", (df_clean['preprocessed'] == '').sum())

# 빈 문자열 제거
df_clean = df_clean[df_clean['preprocessed'] != '']

# 2. 단어 벡터화
vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
doc_term_matrix = vectorizer.fit_transform(df_clean['preprocessed'])

# 3. LDA 모델 학습
lda_model = LatentDirichletAllocation(n_components=5, random_state=42)
lda_output = lda_model.fit_transform(doc_term_matrix)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

전처리 전 NaN 값의 수: 0

<ipython-input-13-3bd4136b0f94>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['preprocessed'] = df_clean['대화'].apply(preprocess_text)

전처리 후 빈 문자열의 수: 1

In [14]:
# 4. 결과 시각화
pyLDAvis.enable_notebook()
vis = pyLDAvis.lda_model.prepare(lda_model, doc_term_matrix, vectorizer)
pyLDAvis.display(vis)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [15]:
# 5. 토픽별 주요 단어 출력
def print_topics(model, vectorizer, top_n=10):
    feature_names = vectorizer.get_feature_names_out()
    for idx, topic in enumerate(model.components_):
        top_features_ind = topic.argsort()[:-top_n - 1:-1]
        top_features = [feature_names[i] for i in top_features_ind]
        weights = topic[top_features_ind]
        print(f"Topic {idx + 1}:")
        for feat, weight in zip(top_features, weights):
            print(f"{feat}: {weight:.4f}")
        print()

print_topics(lda_model, vectorizer)

Topic 1:
오늘: 103.1215
알람: 87.1966
내일: 81.1974
예약: 69.0375
부탁: 65.3047
설정: 57.6482
경기: 50.8519
날씨: 32.1978
시청: 25.1961
축구: 23.1973

Topic 2:
시간: 76.1952
티비: 47.1974
노래: 46.5320
지금: 44.7090
공기: 29.1992
운세: 28.1934
자동: 26.4191
세탁: 26.2345
명상: 25.1978
빌보드: 25.0434

Topic 3:
예약: 44.2590
빨래: 35.9396
이번: 33.7117
일정: 27.6957
체조: 26.2121
재생: 25.4207
언제: 25.1975
건강: 23.1997
확인: 23.0672
회전: 22.1993

Topic 4:
모드: 91.1979
지금: 84.6869
외출: 80.1995
뉴스: 70.2537
이제: 44.1968
방범: 43.1994
채널: 26.2468
방송: 23.8292
설법: 23.2440
보일러: 21.1993

Topic 5:
메시지: 65.1409
전화: 56.1971
번호: 49.1975
로또: 45.1908
메일: 40.1966
다음: 40.1939
문제: 32.1978
예약: 26.3030
자막: 26.2253
산수: 26.1987

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)