In [2]:
import numpy as np
import pandas as pd

In [3]:
path="/content/drive/MyDrive/mulcam_bigdata/3조 : 최종 프로젝트/공용/AI명령어 데이터/명령어 음성(노인남여)/AI로봇 데이터_50대_validation.csv"

In [4]:
pd.read_csv(path)

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,나 열 시에는 체크인할 수 있는 거야?,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1001-01-02-LTM-M-04-A.wav
1,이거 어떻게 퇴실해?,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1002-01-02-LTM-M-04-A.wav
2,주차 요금 나온 거 다 보여 줘.,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1003-01-02-LTM-M-04-A.wav
3,주차비를 결제해 주지.,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1004-01-02-LTM-M-04-A.wav
4,아무나 간병인 불러 줄래?,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1005-01-02-LTM-M-04-A.wav
...,...,...,...,...,...,...,...,...
135692,숙소 직원이 직접 와야 할 것 같아.,Female,50~59,서울/인천/경기,경기/서울,가정,가정,e_0355-4996-01-02-LJL-F-07-A.wav
135693,시간당 주차비 안내해 줘.,Female,50~59,서울/인천/경기,경기/서울,가정,가정,e_0355-4997-01-02-LJL-F-07-A.wav
135694,삼십 일에 독감 예방주사 맞게 신생아과 미리 예약 잡아 줘.,Female,50~59,서울/인천/경기,경기/서울,가정,가정,e_0355-4998-01-02-LJL-F-07-A.wav
135695,여기서 서울역까지 가는데 대중교통 배차 시간 어떻게 돼?,Female,50~59,서울/인천/경기,경기/서울,가정,가정,e_0355-4999-01-02-LJL-F-07-A.wav
135696,주차 값 카드로 정산해 줘.,Female,50~59,서울/인천/경기,경기/서울,가정,가정,e_0355-5000-01-02-LJL-F-07-A.wav

In [5]:
raw = pd.read_csv(path)
raw.head()

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,나 열 시에는 체크인할 수 있는 거야?,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1001-01-02-LTM-M-04-A.wav
1,이거 어떻게 퇴실해?,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1002-01-02-LTM-M-04-A.wav
2,주차 요금 나온 거 다 보여 줘.,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1003-01-02-LTM-M-04-A.wav
3,주차비를 결제해 주지.,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1004-01-02-LTM-M-04-A.wav
4,아무나 간병인 불러 줄래?,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1005-01-02-LTM-M-04-A.wav

In [6]:
df = raw.copy()
df.head()

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,나 열 시에는 체크인할 수 있는 거야?,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1001-01-02-LTM-M-04-A.wav
1,이거 어떻게 퇴실해?,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1002-01-02-LTM-M-04-A.wav
2,주차 요금 나온 거 다 보여 줘.,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1003-01-02-LTM-M-04-A.wav
3,주차비를 결제해 주지.,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1004-01-02-LTM-M-04-A.wav
4,아무나 간병인 불러 줄래?,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1005-01-02-LTM-M-04-A.wav

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135697 entries, 0 to 135696
Data columns (total 8 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   대화      135697 non-null  object
 1   성별      135697 non-null  object
 2   연령대     135697 non-null  object
 3   지역      135697 non-null  object
 4   사투리     135697 non-null  object
 5   녹음환경    135697 non-null  object
 6   소음환경    135697 non-null  object
 7   파일이름    135697 non-null  object
dtypes: object(8)
memory usage: 8.3+ MB

#LDA 분석

In [8]:
!pip install -q pandas numpy scikit-learn konlpy pyLDAvis

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 89.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 86.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 36.6 MB/s eta 0:00:00

In [9]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis.lda_model

# 1. 텍스트 전처리
def preprocess_text(text):
    okt = Okt()
    tokens = okt.nouns(text)  # 명사만 추출
    return ' '.join(tokens)

df['preprocessed'] = df['대화'].apply(preprocess_text)

# 2. 단어 벡터화
vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
doc_term_matrix = vectorizer.fit_transform(df['preprocessed'])

# 3. LDA 모델 학습
lda_model = LatentDirichletAllocation(n_components=5, random_state=42)
lda_output = lda_model.fit_transform(doc_term_matrix)

In [10]:
# 4. 결과 시각화
pyLDAvis.enable_notebook()
vis = pyLDAvis.lda_model.prepare(lda_model, doc_term_matrix, vectorizer)
pyLDAvis.display(vis)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [11]:
# 5. 토픽별 주요 단어 출력
def print_topics(model, vectorizer, top_n=10):
    for idx, topic in enumerate(model.components_):
        print(f"Topic {idx + 1}:")
        print([(vectorizer.get_feature_names_out()[i], topic[i])
                for i in topic.argsort()[:-top_n - 1:-1]])

print_topics(lda_model, vectorizer)

Topic 1:
[('숙박', 12942.801135572674), ('예약', 11143.994855995483), ('호텔', 7744.190051401727), ('체크아웃', 3593.1967177774254), ('근처', 3577.504262233741), ('시설', 3149.609266963746), ('확인', 2955.5603206214064), ('변경', 2336.1740381339864), ('주변', 1941.5909296538034), ('공항', 1902.7272630154498)]
Topic 2:
[('병원', 10518.377480684196), ('주차', 4600.494352618592), ('어디', 3894.426371586869), ('요금', 3788.317966954504), ('시설', 3650.789109777444), ('간병인', 3498.195483201205), ('위치', 3211.616744610435), ('지도', 2757.0684620935695), ('정산', 2363.19801753539), ('차비', 2297.1941235647)]
Topic 3:
[('예약', 13902.248751878355), ('시간', 10446.644067961837), ('병원', 10323.804196688136), ('숙소', 5638.773344123371), ('진료', 4512.762723168427), ('버스', 3466.1957947339956), ('배차', 2731.1977385635105), ('취소', 2225.1993146485925), ('관계자', 1955.998983704592), ('가능', 1795.0006061083152)]
Topic 4:
[('확인', 5666.474937841727), ('진료', 4910.636489153653), ('언제', 3857.754120192817), ('예약', 3715.3557465716935), ('체크', 3618.7830121223565), ('시간', 3397.6403265784916), ('내과', 3301.1983125780816), ('오늘', 2279.0601545309382), ('식당', 2119.0922505231783), ('선생님', 1865.1981459678598)]
Topic 5:
[('직원', 4309.612005179383), ('간호사', 3875.4264229683226), ('얼마', 3814.1967172901755), ('호출', 3812.62047296056), ('주차', 3567.904116927619), ('여기', 3544.6986675944045), ('지금', 3210.7760268923857), ('차비', 3203.190528947254), ('관광지', 3151.002196475495), ('요금', 2994.080246094103)]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

#중복 제거 값 LDA 분석

In [12]:
# 중복 제거
df_clean = df.drop_duplicates(subset=["대화"])
df_clean.reset_index(drop=True, inplace=True)
df_clean.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름,preprocessed
0,나 열 시에는 체크인할 수 있는 거야?,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1001-01-02-LTM-M-04-A.wav,나 열 시 체크 수
1,이거 어떻게 퇴실해?,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1002-01-02-LTM-M-04-A.wav,거 퇴
2,주차 요금 나온 거 다 보여 줘.,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1003-01-02-LTM-M-04-A.wav,주차 요금 거
3,주차비를 결제해 주지.,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1004-01-02-LTM-M-04-A.wav,차비 결제 주지
4,아무나 간병인 불러 줄래?,Male,20~29,서울/인천/경기,경기/서울,사무실,사무실,CE0271-1005-01-02-LTM-M-04-A.wav,아무나 간병인 줄

In [13]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4988 entries, 0 to 4987
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   대화            4988 non-null   object
 1   성별            4988 non-null   object
 2   연령대           4988 non-null   object
 3   지역            4988 non-null   object
 4   사투리           4988 non-null   object
 5   녹음환경          4988 non-null   object
 6   소음환경          4988 non-null   object
 7   파일이름          4988 non-null   object
 8   preprocessed  4988 non-null   object
dtypes: object(9)
memory usage: 350.8+ KB

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [14]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis
import pyLDAvis.lda_model

# 1. 텍스트 전처리
def preprocess_text(text):
    if pd.isna(text):
        return ""
    okt = Okt()
    tokens = okt.nouns(str(text))  # 문자열로 변환
    return ' '.join(tokens)

# NaN 값 확인
print("전처리 전 NaN 값의 수:", df_clean['대화'].isna().sum())

# 전처리 적용
df_clean['preprocessed'] = df_clean['대화'].apply(preprocess_text)

# 전처리 후 빈 문자열 확인
print("전처리 후 빈 문자열의 수:", (df_clean['preprocessed'] == '').sum())

# 빈 문자열 제거
df_clean = df_clean[df_clean['preprocessed'] != '']

# 2. 단어 벡터화
vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
doc_term_matrix = vectorizer.fit_transform(df_clean['preprocessed'])

# 3. LDA 모델 학습
lda_model = LatentDirichletAllocation(n_components=5, random_state=42)
lda_output = lda_model.fit_transform(doc_term_matrix)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

전처리 전 NaN 값의 수: 0

<ipython-input-14-3bd4136b0f94>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['preprocessed'] = df_clean['대화'].apply(preprocess_text)

전처리 후 빈 문자열의 수: 0

In [15]:
# 4. 결과 시각화
pyLDAvis.enable_notebook()
vis = pyLDAvis.lda_model.prepare(lda_model, doc_term_matrix, vectorizer)
pyLDAvis.display(vis)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [16]:
# 5. 토픽별 주요 단어 출력
def print_topics(model, vectorizer, top_n=10):
    feature_names = vectorizer.get_feature_names_out()
    for idx, topic in enumerate(model.components_):
        top_features_ind = topic.argsort()[:-top_n - 1:-1]
        top_features = [feature_names[i] for i in top_features_ind]
        weights = topic[top_features_ind]
        print(f"Topic {idx + 1}:")
        for feat, weight in zip(top_features, weights):
            print(f"{feat}: {weight:.4f}")
        print()

print_topics(lda_model, vectorizer)

Topic 1:
예약: 1085.1876
진료: 352.1987
시간: 345.4846
병원: 271.6362
숙박: 215.7451
확인: 172.3811
언제: 159.7840
변경: 138.1959
내과: 124.1964
오늘: 122.1936

Topic 2:
주차: 318.1987
요금: 277.1833
차비: 194.1991
얼마: 165.1975
체크: 148.7049
지금: 118.5324
확인: 117.4245
직원: 112.6121
숙박: 109.9337
병원: 77.2141

Topic 3:
병원: 224.4602
간병인: 143.1981
지도: 124.1939
어디: 106.8055
여기: 94.2582
관계자: 81.1980
달라: 80.0607
식당: 77.1965
취소: 70.1529
날짜: 69.1926

Topic 4:
안내: 226.8623
호텔: 226.2687
버스: 150.3703
근처: 146.6166
시간: 139.6048
주변: 130.9574
관광지: 126.1980
배차: 116.1992
숙소: 100.3162
병원: 99.0572

Topic 5:
시설: 238.1970
숙박: 142.3751
체크아웃: 135.1972
숙소: 129.0789
병원: 109.6322
정보: 106.1962
간호사: 94.2823
이용: 77.1923
위치: 58.5523
상품: 58.3517

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)