In [1]:
import numpy as np
import pandas as pd

In [2]:
path="/content/drive/MyDrive/mulcam_bigdata/3조 : 최종 프로젝트/공용/AI명령어 데이터/명령어 음성(노인남여)/AI비서 데이터_50대_training.csv"

In [3]:
pd.read_csv(path)

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,보고 있는 영상 정지시켜 줘.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6001-01-01-KCY-F-05-A.wav
1,다음 주까지 날씨가 어때?,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6002-01-01-KCY-F-05-A.wav
2,나 대신 점등해 줘.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6003-01-01-KCY-F-05-A.wav
3,이번 주 대체로 흐린지 궁금해.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6004-01-01-KCY-F-05-A.wav
4,지금 당장 취침 등 꺼 줘.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6005-01-01-KCY-F-05-A.wav
...,...,...,...,...,...,...,...,...
630183,이후 칠일간 날씨 어떨거래?,Male,40~49,부산/대구/울산/경상,경상,가정,가정,script1_i_0350-8996-01-01-PSH-M-06-D.wav
630184,오디오북 오 분 뒤에 꺼 줘.,Male,40~49,부산/대구/울산/경상,경상,가정,가정,script1_i_0350-8997-01-01-PSH-M-06-D.wav
630185,일요일의 강수량의 퍼센트는?,Male,40~49,부산/대구/울산/경상,경상,가정,가정,script1_i_0350-8998-01-01-PSH-M-06-D.wav
630186,지금 퇴근하니까 보일러 온도 올려 줄래?,Male,40~49,부산/대구/울산/경상,경상,가정,가정,script1_i_0350-8999-01-01-PSH-M-06-D.wav
630187,오디오북 몇시간 남았는지 부탁해.,Male,40~49,부산/대구/울산/경상,경상,가정,가정,script1_i_0350-9000-01-01-PSH-M-06-D.wav

In [4]:
raw = pd.read_csv(path)
raw.head()

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,보고 있는 영상 정지시켜 줘.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6001-01-01-KCY-F-05-A.wav
1,다음 주까지 날씨가 어때?,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6002-01-01-KCY-F-05-A.wav
2,나 대신 점등해 줘.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6003-01-01-KCY-F-05-A.wav
3,이번 주 대체로 흐린지 궁금해.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6004-01-01-KCY-F-05-A.wav
4,지금 당장 취침 등 꺼 줘.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6005-01-01-KCY-F-05-A.wav

In [5]:
df = raw.copy()
df.head()

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름
0,보고 있는 영상 정지시켜 줘.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6001-01-01-KCY-F-05-A.wav
1,다음 주까지 날씨가 어때?,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6002-01-01-KCY-F-05-A.wav
2,나 대신 점등해 줘.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6003-01-01-KCY-F-05-A.wav
3,이번 주 대체로 흐린지 궁금해.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6004-01-01-KCY-F-05-A.wav
4,지금 당장 취침 등 꺼 줘.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6005-01-01-KCY-F-05-A.wav

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630188 entries, 0 to 630187
Data columns (total 8 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   대화      630188 non-null  object
 1   성별      630188 non-null  object
 2   연령대     630188 non-null  object
 3   지역      630188 non-null  object
 4   사투리     630188 non-null  object
 5   녹음환경    630188 non-null  object
 6   소음환경    630188 non-null  object
 7   파일이름    630188 non-null  object
dtypes: object(8)
memory usage: 38.5+ MB

#LDA 분석

In [7]:
!pip install -q pandas numpy scikit-learn konlpy pyLDAvis

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 25.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 86.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 35.5 MB/s eta 0:00:00

In [8]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis.lda_model

# 1. 텍스트 전처리
def preprocess_text(text):
    okt = Okt()
    tokens = okt.nouns(text)  # 명사만 추출
    return ' '.join(tokens)

df['preprocessed'] = df['대화'].apply(preprocess_text)

# 2. 단어 벡터화
vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
doc_term_matrix = vectorizer.fit_transform(df['preprocessed'])

# 3. LDA 모델 학습
lda_model = LatentDirichletAllocation(n_components=5, random_state=42)
lda_output = lda_model.fit_transform(doc_term_matrix)

In [9]:
# 4. 결과 시각화
pyLDAvis.enable_notebook()
vis = pyLDAvis.lda_model.prepare(lda_model, doc_term_matrix, vectorizer)
pyLDAvis.display(vis)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [10]:
# 5. 토픽별 주요 단어 출력
def print_topics(model, vectorizer, top_n=10):
    for idx, topic in enumerate(model.components_):
        print(f"Topic {idx + 1}:")
        print([(vectorizer.get_feature_names_out()[i], topic[i])
                for i in topic.argsort()[:-top_n - 1:-1]])

print_topics(lda_model, vectorizer)

Topic 1:
[('내일', 30478.61014001467), ('사고', 24943.054421589448), ('블라인드', 23561.199308875883), ('날씨', 18083.68421493583), ('즐겨찾기', 16307.415564899844), ('노래', 10954.19849437439), ('예보', 9774.197983128372), ('확인', 9633.95064981274), ('이번', 8295.125199546941), ('다음', 5476.042125749227)]
Topic 2:
[('모드', 26854.190152976305), ('취침', 19526.19821926702), ('경기', 18953.670027943048), ('절약', 16430.19939531402), ('에너지', 14901.199401983118), ('일정', 14693.020474690591), ('온도', 13997.410819002933), ('오디오북', 13607.47586336041), ('설정', 13562.831863431724), ('목소리', 11427.199129260202)]
Topic 3:
[('오늘', 32418.032891669238), ('뉴스', 26330.19965158547), ('환율', 16703.986375414104), ('플레이', 15467.199216114699), ('리스트', 14706.199252143548), ('확인', 13296.79333841566), ('주요', 13202.199772032638), ('주가', 12116.93743129753), ('지금', 10748.488913518384), ('언제', 10170.194261938903)]
Topic 4:
[('커피', 34111.19930493216), ('오디오북', 21126.513671295474), ('머신', 18075.199666261316), ('토스터', 15239.199350022483), ('시간', 13380.993375626014), ('공기청정기', 12356.266779465119), ('콘텐츠', 11202.199282825857), ('티브이', 10962.198692844022), ('지금', 8301.558311434046), ('재생', 7396.1423205412575)]
Topic 5:
[('지금', 30839.43390599243), ('현재', 23786.842240073936), ('상황', 20921.198671101636), ('교통', 20435.19896392791), ('주말', 19875.355447531085), ('날씨', 17693.637712455926), ('경로', 13024.197673994791), ('속도', 12046.192617694976), ('오디오북', 11258.608937696428), ('추천', 10690.19817466848)]

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

#중복 제거 값 LDA 분석

In [11]:
# 중복 제거
df_clean = df.drop_duplicates(subset=["대화"])
df_clean.reset_index(drop=True, inplace=True)
df_clean.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,대화,성별,연령대,지역,사투리,녹음환경,소음환경,파일이름,preprocessed
0,보고 있는 영상 정지시켜 줘.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6001-01-01-KCY-F-05-A.wav,보고 영상 정지
1,다음 주까지 날씨가 어때?,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6002-01-01-KCY-F-05-A.wav,다음 주 날씨
2,나 대신 점등해 줘.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6003-01-01-KCY-F-05-A.wav,나 대신 점등
3,이번 주 대체로 흐린지 궁금해.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6004-01-01-KCY-F-05-A.wav,이번 주 대체로
4,지금 당장 취침 등 꺼 줘.,Female,30~39,서울/인천/경기,전라,가정,가정,script1_g_0249-6005-01-01-KCY-F-05-A.wav,지금 당장 취침 등

In [12]:
df_clean.info()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13670 entries, 0 to 13669
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   대화            13670 non-null  object
 1   성별            13670 non-null  object
 2   연령대           13670 non-null  object
 3   지역            13670 non-null  object
 4   사투리           13670 non-null  object
 5   녹음환경          13670 non-null  object
 6   소음환경          13670 non-null  object
 7   파일이름          13670 non-null  object
 8   preprocessed  13670 non-null  object
dtypes: object(9)
memory usage: 961.3+ KB

In [13]:
import pandas as pd
import numpy as np
from konlpy.tag import Okt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis
import pyLDAvis.lda_model

# 1. 텍스트 전처리
def preprocess_text(text):
    if pd.isna(text):
        return ""
    okt = Okt()
    tokens = okt.nouns(str(text))  # 문자열로 변환
    return ' '.join(tokens)

# NaN 값 확인
print("전처리 전 NaN 값의 수:", df_clean['대화'].isna().sum())

# 전처리 적용
df_clean['preprocessed'] = df_clean['대화'].apply(preprocess_text)

# 전처리 후 빈 문자열 확인
print("전처리 후 빈 문자열의 수:", (df_clean['preprocessed'] == '').sum())

# 빈 문자열 제거
df_clean = df_clean[df_clean['preprocessed'] != '']

# 2. 단어 벡터화
vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
doc_term_matrix = vectorizer.fit_transform(df_clean['preprocessed'])

# 3. LDA 모델 학습
lda_model = LatentDirichletAllocation(n_components=5, random_state=42)
lda_output = lda_model.fit_transform(doc_term_matrix)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

전처리 전 NaN 값의 수: 0

<ipython-input-13-3bd4136b0f94>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['preprocessed'] = df_clean['대화'].apply(preprocess_text)

전처리 후 빈 문자열의 수: 11

In [14]:
# 4. 결과 시각화
pyLDAvis.enable_notebook()
vis = pyLDAvis.lda_model.prepare(lda_model, doc_term_matrix, vectorizer)
pyLDAvis.display(vis)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [15]:
# 5. 토픽별 주요 단어 출력
def print_topics(model, vectorizer, top_n=10):
    feature_names = vectorizer.get_feature_names_out()
    for idx, topic in enumerate(model.components_):
        top_features_ind = topic.argsort()[:-top_n - 1:-1]
        top_features = [feature_names[i] for i in top_features_ind]
        weights = topic[top_features_ind]
        print(f"Topic {idx + 1}:")
        for feat, weight in zip(top_features, weights):
            print(f"{feat}: {weight:.4f}")
        print()

print_topics(lda_model, vectorizer)

Topic 1:
오디오북: 902.1988
취침: 488.1990
모드: 361.9239
오디오: 353.1990
설정: 321.1957
콘텐츠: 273.1994
속도: 259.1996
목소리: 237.1994
지금: 219.3665
시간: 217.4650

Topic 2:
지금: 625.5641
내일: 570.1961
날씨: 504.0017
현재: 442.1873
교통: 377.1980
상황: 367.1978
확인: 350.3041
온도: 343.8478
보일러: 275.5683
경기: 259.1533

Topic 3:
이번: 564.1243
환율: 375.6532
리스트: 289.1992
경로: 281.1981
플레이: 279.1995
추천: 214.1980
확인: 209.9292
언제: 194.4495
지금: 184.6649
날씨: 164.1757

Topic 4:
오늘: 645.8630
뉴스: 626.1991
즐겨찾기: 307.4804
주요: 291.1994
노래: 258.1937
얼마나: 251.0747
모드: 212.4750
절약: 185.3739
에너지: 157.1931
날씨: 145.4220

Topic 5:
커피: 675.1984
사고: 552.2667
블라인드: 382.8055
머신: 373.1990
토스터: 348.1990
시간: 255.9304
공기청정기: 196.5392
티비: 195.5037
토스트: 143.1987
확인: 126.3046

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)